# Generated by Django 5.1 on 2024-08-31 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department'),
        ),
    ]
