# Generated by Django 5.1 on 2024-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_age_employee_day_employee_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='day',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='month',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='year',
        ),
        migrations.AddField(
            model_name='employee',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
