# Generated by Django 5.1 on 2024-09-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_dateofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='employee',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='year',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
